### ISSUE TITLE
Crash on Malformed 8-bit Terminal Output

### ISSUE THREAD

**Issue by CMB** [tspivey/tdsr#12]
tdsr crashes if the thing displayed on the screen is not well-formed UTF-8.
To reproduce: start tdsr, and run:
echo -ne '\xf3'
to see a traceback.

Spotted on both Mac and Linux.

Don't know of a really clean fix for this at the moment.

**Comment by tspivey** [comment]
We should be able to run with the incremental decoder's error mode set to replace:

    decoder = codecs.getincrementaldecoder('utf-8')(errors='replace')

I'm testing with that, though screen seems to avoid the issue.
