### ISSUE TITLE
crash on Ventura Beta.

### ISSUE THREAD

**Issue by paxcoder** [tspivey/tdsr#23]
Hi.
Please test it against the new beta, macOS 13.0, and you will get constant crashes, especially while typing.

**Comment by paxcoder** [comment]
@tspivey please answer

**Comment by tspivey** [comment]
If it worked pre-beta and it fails in the beta, then it's a bug in the beta.

**Comment by paxcoder** [comment]
It worked prior installing the beta, but it seems that they deprecated lots of stuff.
