### ISSUE TITLE
Control key fails to stop speech under Mac OS ventura

### ISSUE THREAD

**Issue by arfy8820** [tspivey/tdsr#28]
Fairly simple. Pressing control does not interrupt speech, as you would expect. However, any other key does interrupt speech just fine. Fairly sure this worked under Monterey and earlier. Have checked that both pyte and pyobjc are both latest versions, from pip.

**Comment by tspivey** [comment]
Terminals don't send anything for Control on its own. Control used to stop speech in other applications when VO was running, not just VO. Now it doesn't, so you'll have to use Option-x.

**Comment by arfy8820** [comment]
Ok, no problem! I did wonder if it might have been an OS change, and thanks for reminding me of option-x.
