### ISSUE TITLE
Repeated symbols handling

### ISSUE THREAD

**Issue by hbk619** [tspivey/tdsr#34]
Currently TDSR reads symbols one by one e.g for Pytest output the total tests is surrounded by equals symbols so TDSR reads "equals equals equals equals equals". Some screen readers tell you the count and the symbols e.g. "5 equals". It would be cool if TDSR did that too. I've made  a [commit on my fork](https://github.com/hbk619/tdsr/commit/773b372d9fe4200061e54ac14fa39bb2aa50fc66) and it works well. I could make it optional based on config if that's preferred. What do you think?

**Comment by ChrisDuffley** [comment]
I'd like to see this as a config option.

Thanks!
